# Generated by Django 3.0.5 on 2023-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('question_number', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('exam_time', models.IntegerField(max_length=20)),
            ],
        ),
    ]
