# Generated by Django 3.0.5 on 2023-11-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0010_auto_20231120_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursenotes',
            name='teacher',
        ),
    ]
